name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      XDEBUG_MODE: coverage
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: run PHPUnit tests
        run: |
          ./vendor/bin/phpunit --testdox --coverage-clover clover.xml
      - name: phpunit-coverage-badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
