name: Check Tests are passing

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: run PHPUnit
        run: |
          ./vendor/bin/phpunit --testdox
